[package]
name = "bevy_gpu_fluid"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.16.1"
glam = "0.30.5"
bytemuck = "1.23.1"

[dev-dependencies]
criterion = "0.7.0"

[[bench]]
name = "step_benches"
harness = false
