name: Rust CI

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test

      # Installing system libs that Bevy's audio backend needs
      # ran to an error without it
      - name: Install ALSA dev libs
        run: sudo apt-get update && sudo apt-get install -y pkg-config libasound2-dev

      - run: cargo test